[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#111111"
linkColor = "#111111"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#111111"